function findgemstones(gems){
	
	var iter=0,
		superset="abcdefghijklmnopqrstuvwxyz";
	
	for(iter;iter<gems.length;iter++){
		superset=findSuperSet(superset,gems[iter]);
	}
	
	return superset.length;
	
	function findSuperSet(previousSuperSet,newSet){
		var iter=0,
			newSuperSet=[];
	
		for(iter;iter<newSet.length;iter++){
			if(isPartOfPreviousSuperSet(newSet[iter]) && newSuperSet.indexOf(newSet[iter])===-1){
				newSuperSet.push(newSet[iter])
			}
		}
		
		return newSuperSet;
		
		function isPartOfPreviousSuperSet(character){
			return previousSuperSet.indexOf(newSet[iter])!==-1;
		}
	}
}

function parseInput(text){
	var lines=text.split("\n").slice(1);
	
	console.log(findgemstones(lines));
	
}

var text="100
abwmfhjirnlcgbhmleckbdqb
akbsyjcxjenwaennqjeigwrfkpdbonfclucknfdlxpqeibsblmdbukkhgqvmsqmyxcxpepwraoswimgolmcbghrhkqbdlytjhl
aemgnwwjfcffcbkhgddgidl
mbtssowrdqegqiannnyvmgajbfdnglkzcshxouplqwkcoq
yualdithbdjduakggiminefdjabwuymqutlmmbndcxunelykerwckremmx
rdudnthupqhjzzddhuyjofppbxmieypjmmpllrapfwlaggaqkibccbwagalxodcnuvneohowkp
peacehqbqeltcvsirnlnhjskihkrlzxjbffdmzdgf
wazffivcijdzmgdoaegbgeulwwvqjfhpslwjxwfupepuaibkgzubdawqibjcdvuhevqbgczynydduvrmyzwpdbvyvjxyp
owjemukgihbndvvcfaoxlyxsmhpbocrebnqffsgtujardjvryxpriuqbknnldpuaeugdkhpgdxjfbizlstrnwxf
skohflwrojdasinmpvkkjfonjmbbgjfacxemdpcq
tdxgsnfqqlvkcqxlmwabinqalcehxjcajwtijrqbiycrxevgpefmndfvhpazurjdvqwdhwhcodebzgzkdshexv
vllzxfnuajpewvgwpyugmxzhxchcklbrrhjqdfwajvubjjifioedpryidsfjzrflnucbkgqahyh
fnfcttcmgbhodykbnpggualxawsrajtdjvwzntpmrjgeif
ktfiknzpvrnsydqfwnaqmfviqczjslrbaezagbbdndghtmqywtcbjgccmlijczcwva
oggkpwbqlzeqnosshztoctlkqqbnkrzdgazmmlfazyekafcxhadblnnfxlosipvlienmkjlj
zevxpmayjspjnjdtcdnynkbtbfetdxisqfuthelgwbaz
ldielbdqfpzksjmnahwcidteeagtowkhfsvbn
oszskkekcyxvxbfvsbgexgjditqxhdflcgylzmmatwcipffcbsnhelmpoaiji
atxkqniujcimggnbaelzdckmmxiwaacvfnwylsaoanviqshknpw
gmbdfljchkbninxyczaeje
mrdkdixbqicahigkferxaymwqnghnxgcijhwfllkb
hibnktmvxkzgbahqmvctcrgeewmrtpqwjlwqaellfceiuuxkadsprpkbfarggo
ismauabopfhtvulxjsqheqsqjibdxcrwgnfdozbeoqoxmyubukdbkrwjdrkketotffrsnqwpiegcaptlinqirwpchlpspmvlq
qslotyehovmufqewlunsltfopqddruudyrhaulyiklqjsrfvyneyjqkgezpneyflhmehzivacegjjoslgxbyqrk
oppnteksnokmispqtetgleiqiptqxeahsmuctadyyrulljrfliofqywusuzxqggtbnrfmdeodaobnubfq
fcgjjansoyhekkckoieludfywbtpavisrceamkcyvfujk
tbmuftansxkmeimvvgwiefmwgeasdinhrfkgkxymkqhpppfnyqhuflyjlmqpleejqsoidnagaazfawwxhoemndcelf
immkrbfujnrfcphgnmabtdxeuledkm
admbiiwlmkrmoihlivxlhbptqvadfykqpkdhqwxcasccjzgceddcdpweiaztqijyecmafwixnmjhsxevtbgqnbkjkk
obugujtkhlhqhchizrgijygnmyjagtubwkqlvflqfgijxypmtuvmendjpzdwb
qfrwbmphilvebczedwxdacictezvqkzknldrzobhcgzuvrnhreqderhdgkflsvqgxvfdtwatvkyiuoodxxuvjxygdcoem
jmindpagqhejbqeknemqdsivctalmyxcwfec
ukrgcbnffjkcapfoadihiegml
fbacopgfjgeijdgfobyoxnkijsfpphuxoehtphsawtlcvesqntdgudrlwdgpzqigycfbwcxsbnuxxukbwilzafvmpm
mmgfcacvylgiyjveahpaybpudzydakxlmhepniueazbn
aelecidzfhjbggkzifwnmxmnk
lvficlkkmyczmdzdezlrblmcvbiufabxgxuxchpynvwvrzsbhluvexnkzpkkosgokqjwwdqlktfbctmezzzobyrieawyettol
ljflcmgrsiobwzcmmdpwbimrfzkkjibdfsavrbhegahzdqftvyjsyonnecdzkvjb
nqgsuetudywjvnatfmdxixcgbcybtnnhalchfmnjskicrtrce
zmuhfvbknstccmwdqbshgezbgtytqgfihsaqfczetulxqaekbtqjmniafomxrsjrzqqinxyk
nechnodpkqhgbyhlsfbfjarddfmfhgxaiiao
peldkvgsijbjftsmmqdgwhgrspigfwieacnxrwtifbbepzmaxjufnqhzvxqqfkzcvtrg
igmnowxxaxaaflihjnkcsjvcmfvdfnchlzlfobxjhbqerldwrhodzxcxfgzedbmhtthalgiaxjolrmdjnsycmmvkimvptoh
nkrenjggfhiqsagripbbebriwnyatbqxlhbmyshxodcykevgicmmwgomjavjocsyhfcleofdfs
rejqeaigqbgkdgoomhcjffhijhrxltnyiairaej
feezgfwjxwlkxmkzmjqiztucihqnwqaihbrisexzizvjrsaddbglmd
jgtjfsacdkmnbllajefenpricidlgmkjevonadh
gntfckeimeafbbslkykjggkibtwyjsknjrqrcmiuhpfweydxqzgmtkfhyarguqkflbajtdsfgxjyyzzdmjxtlncr
famxhjgwarcewneklcbjzaztdaczkpai
knklvlgcuyyadraitfbmdbluheaj
yzsjzwxwqdcmanzntvjjqcjcmhdejhpdxjnkawiaifdlicxkeiciawahcjeteyhywdlulwfjoriejbflhuwgntxbrobqeduqi
ulawfgcxbmcuoogsbsuaxyizcqhgybjemkkhngrqhdqohwlbvmeoonhugdmuambiwjfqffzfdbsebeucblkpndgdpjhaec
cdpqbcaxbprntyxajkmlfhmleitxpvinxinrgyvvgyjjnfmumwllelujddzqxteojkcgmizpkgcbujjxmfayrtrel
bkaikrytemdcaevxtflnhlgjibl
paokvlseysvgneevpqitxhvmjttibikfnnqedlygjhlzukdxxaivppxkvectkilofldujsrryjp
amqpxvlpuigcnihiqgojgtxodjfvdsnhafbvikmmakqlgcldfesdjakrgjnetlsetkfvabecvbnm
hzkwfcwmtmkuryjispcmlrjovzfdbfhefbfguvfciadzcmnhjiigycuyhcqvgywtuuisbgxewnrxkbrokduijmllm
bwbmleedbpeobvcogcvaevjclftdnnipdvixnjdkmbqlzxgclpfuujoicufpvuzadhjqsv
hdlamjgenbkcgif
bszpgxigemdjlfhkbznmasklqomc
pemfzmccgcngyjjnmahtbhkhcixzuxgpogkwyeoxlxqsktaizwmpkdjbypkciker
elkigjfnjcymtbxghbwqsldkoaalz
hcttolgekbiacnljkiqtkojtdrnzdkqqobhkilexcgjfsbctcliyaehvgxijawokfhdapopcgnuxqrzbpnfizzmlmbqiiaasjeoe
waqzyknpelssjqumlwlchkcyijzfouulzjkzuquaixwzzkknfisachrpnrgfoadinbqkkoqsnagypajt
jngwyftbwyjiwdnonawgoqacmkbrecltaukwnrdbfjhvimpehighbouyjeqhckyflxvcbmit
tourddblfifastcgrhtmeeycdlgdoxrihirxxflkskonbejoltlaxemn
aofsbotndceuuwgokfmracltuqddcwfyfvcjpbzbeoutmladcypvmloqocoozfvyimgfcpphpohkvcacwvyi
jdlzavdpihfnnguvceymorycsdmovghglnisnvjcurrasdvbqwimsnezabtvakhkhecbhjgy
dwialxrqbhudpcmgvkhogyxpxscmtfpcmgdyneymwgxybwrhciwkcgcflzmmmjxkltjfbcyjkrxeaykhjiolafac
aegrckdqduhytwqkynesflwdtomtayhbrcekwhjysavvbdflkfaoatxxycphlantvjjcbmkyqjktxfiqrgnm
fkrodchhilugptzrebgzjlnsmgqkqfhadewjbygagiocdvxiifcojkioaoa
oamhjasbhaikgccveoanfzlwhd
jgizycbhlnacdiwedkjltplhfevegzafdbgdigxhymqowangd
dcafdbomgejgwqclwoaejklohyhfzmgjblnytmcxuviks
nikvrxjkemdapdcidlbihucbjfgs
pltogxhabedbqnjtmofdaryuejlqjjkbfeldcpddqjimrsrkhgapwhkgbnldciayspskatgfr
nhvktmjjdxaazefisrrijkckmblacggsoqycaps
qywhkitdhrcsgjaubagkgnlcmfudhpoenhikazkebidizpevhkhineffb
jfducvciisarffsuigqbzhpatbsepapbbnatzrhqbzkpswjjrzkxmsfhl
ghgpjfxdkwvsvoenghyvlykalizvjynchtgvbsqmsvfbrofonlcqalgzvabnajfmjnrliyboocwtxnk
pliostikhlyadxykdmnjdbswtaebniwlzkmkovgfjuomwzahmppateophizosqeguzcfumfvfzriyxurmtybwcmdhccpyi
xmmlwmlzreqbbqppmnhlkfspwfqrcvjikuswjqfpvzbejzvdahjbgbxbwpvstdauxmnekkrymlgjqtbzulcsgcthxhasxwihejt
cmyptksbixdidjwngfgqptzowgxkozxnxopuwdpfbczhjqlnyrppyahxhvgblqjlgktimorpktwnmhpiiinzgbbfsjelfhlgmoa
ihulsdzqhkbpfpeaayzkhrgzczyvjrnpudidhveezbxrlcpwejevrhnxgnhutusqymolgzfmkqgyzklg
jsxjbciaklegyyqeyfmjfhhngykfdzi
tmuglhaldsxuqgcklnvdkwvfgzrnzwywpsciercmdfiefalawnybzyzcsjahfdxgdgqqaivsstqyhmihaqgtu
mbyzkylfjiohbgyggxifccidjmgerbjjsshezrinemqafypzjeanl
edsgujqhjklfgksltjjixbvrkimsszgflmdmkjdltrabhsluhdseanmhhgqdgcgfyhmmfowyybwkmzmwjl
qpsqwldrwamkbkggmeakhtpifgjlalejgilwarcnaeccmgxpogbhfqsohdxgmqexcsmljzzaaukduydmwjhgnjqiztx
qebabcgnpkligdjpkemmuvfmhrlqfpjfwb
uiaognvlgvzoenahzkgbjtfqaljsqtqtpltrhbkaelfodiydcxmkvxwdpaxzxqmauhr
hjycfehnvipaefalbdujelwcydthwifugoibbfgzssfmhgkponmeldcatbdeiwbcn
lafyejhkcqmngefixjbdytbb
ghouhgkekvfrdxjgbrbjqaoglgixrynpqdulghnfkqmaapstrlffkojrbhckumxglaqkgxgotxdjsqedkq
icsgaujjgnzaqtwubeeiualvaxfddcvozmsndmkwbqowqlztnoeuyuthlnlpuih
zmhaihrcgspswunbiwyufadffittrhpijgtbizyfcswwfirglfvkzlsnivesdmjwqnjxvgrqn
cheocduyiadqhkknfftyiktbboxhkjbvmrdjlvjxkmlwngsqjs
ebzfnsfeelaraqcdfajmcumcftvihwhzndaakioelkkhg
ealcchkytdygcafziaxiydjluxdqzbnronconnahqguedyfegioaqgffmvmbw
gnmbukdxcsticibdxkpyoarlgjxekqnailrfsahd";